name: LGU Web Validation and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Data Validator
        run: python scripts/validate_data.py

      - name: Run Unit Tests
        run: python -m unittest discover -s tests/
